use wikt;

INSERT INTO `lang` (`name`, `abr`) VALUES ('English', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Latin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Scots', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Guernésiais', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Indonesian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Irish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Jèrriais', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lojban', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Malay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Romanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Scottish Gaelic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dutch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Afrikaans', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Catalan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Danish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Italian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Norwegian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Spanish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Swedish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('French', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old English', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Saxon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Portuguese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Limburgish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle English', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle French', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old French', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cornish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Polish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Esperanto', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Latvian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mandarin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Translingual', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('American Sign Language', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Azeri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Finnish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('German Sign Language', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Luxembourgish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Norwegian Bokmål', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Norwegian Nynorsk', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Slovene', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Somali', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Turkish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Vietnamese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Welsh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ewe', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maltese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Crimean Tatar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kurdish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mapudungun', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tagalog', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tatar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Uzbek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Walloon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Estonian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Faroese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Interlingua', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Interlingue', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Serbo-Croatian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Slovak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sundanese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Occitan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lithuanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Volapük', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zazaki', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gothic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hungarian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Japanese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Manx', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Novial', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('South Marquesan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Swahili', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Venetian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wuvulu-Aua', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zulu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Navajo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Irish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aynu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Livonian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old High German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Provençal', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pumpokol', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Romani', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ido', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hiligaynon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Marshallese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sardinian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lombard', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cantonese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hakka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Korean', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Min Nan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Okinawan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Czech', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dutch Low Saxon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('German Low German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Romansch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Turkmen', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wik-Mungkan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Greek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Albanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ama', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aromanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dalmatian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Elfdalian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mauritian Creole', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Neapolitan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Dutch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Saterland Frisian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sicilian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tok Pisin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Galician', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('West Frisian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aragonese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Asturian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Fala', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Guaraní', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ladin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Tupi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Papiamentu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Georgian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Crimean Gothic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Murrinh-Patha', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kiput', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yola', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Haitian Creole', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Jersey Dutch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ladino', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Low German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Portuguese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sranan Tongo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tarantino', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('ǃKung', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Breton', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Icelandic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kott', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Dutch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Frisian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Swedish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kven', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gallo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Basque', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Classical Nahuatl', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lower Sorbian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maori', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Meriam', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rapa Nui', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tahitian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tongan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tuvaluan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nigerian Pidgin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rohingya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tolai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mirandese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Baure', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Istriot', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mohegan-Pequot', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pennsylvania German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle High German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Afar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Borôro', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Extremaduran', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hawaiian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Low German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Samoan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Norman', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mangarevan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Niuean', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rarotongan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tikopia', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tokelauan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tuamotuan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Adangme', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bislama', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Friulian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Latgalian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pijin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sirionó', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tupinambá', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alemannic German', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Inari Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kaingang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chinook Jargon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Torres Strait Creole', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ancient Greek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Amuzgo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Balinese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Prussian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Vilamovian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Istro-Romanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Russian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ukrainian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Karelian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Votic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ingrian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Irish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hindi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sanskrit', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ilocano', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Malagasy', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hebrew', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Picard', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Biak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tocharian B', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Adnyamathanha', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Luhya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Luo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Western Apache', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hmong', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kanuri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Indo-Portuguese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Norse', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gilbertese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Silesian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tachelhit', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Buginese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Egyptian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gaulish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Jamaican Creole', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Palenquero', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tacana', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Warao', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Assan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Greenlandic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lavukaleve', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Welsh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cahuilla', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tetum', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tocharian A', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Inuktitut', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kedah Malay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Quechua', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pipil', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Selaru', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Simeulue', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Acholi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Arin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cimbrian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chickasaw', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Louisiana Creole French', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Fijian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Upper Sorbian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wiradhuri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Chinese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mayangna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Skolt Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mandinka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chiricahua', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kashubian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Abau', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alabama', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ojibwe', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('North Frisian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Roro', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Apalaí', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Araki', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hiri Motu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kriol', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kuna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Piedmontese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pitjantjatjara', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Seri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Baluan-Pam', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lou', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aymara', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Welsh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bakung', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Palauan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rennellese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yucatec Maya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('O\'odham', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ainu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wiyot', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tz\'utujil', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Fwâi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Haeke', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Haveke', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Jawe', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nemi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nyâlayu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pije', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yuaga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Annobonese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nauruan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mizo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nias', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Serui-Laut', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wandamen', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zhuang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chamicuro', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Miskito', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Iban', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nalca', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Jarai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Vandalic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tswana', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Banjarese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Javanese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kapampangan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mori Bawah', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Moronene', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Javanese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sasak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Totoli', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Melanau', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Betawi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wangaaybuwan-Ngiyambaa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Baram Kayan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Batak Dairi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Batak Karo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Batak Toba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bintulu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cebuano', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kelabit', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ngaju', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Fiji Hindi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Shona', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('West Coast Bajau', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yoruba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yankunytjatjara', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Krisa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Panyjima', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Amanab', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Veps', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Irarutu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Onin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Uruangnirin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wolof', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dogrib', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Sotho', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sotho', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hausa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Catawba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Karipúna Creole French', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Franco-Provençal', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Belarusian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bulgarian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Macedonian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Michif', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Amis', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Taroko', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ngarrindjeri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Luganda', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Minangkabau', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Isthmus Zapotec', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gagauz', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dena\'ina', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Angolar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Corsican', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Garifuna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ch\'orti\'', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cuiba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Taos', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sonsorolese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tai Dam', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Chinese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Church Slavonic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Adyghe', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chechen', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ingush', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Itelmen', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tajik', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Buyeo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Samoan Plantation Pidgin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Literary Chinese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khitan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Marathi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Min Dong', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bilba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Spanish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Malaccan Creole Portuguese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chamorro', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Golin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Abenaki', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rotuman', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Arabela', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ambonese Malay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Achuar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aguaruna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Waskia', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yup\'ik', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Romagnol', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cia-Cia', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kedang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nahuatl', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Choctaw', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yatzachi Zapotec', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yiddish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Anuta', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dakota', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Palu\'e', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sawi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Arabic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lampung Api', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Akkala Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sabu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Karitiâna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Võro', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bunun', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lamaholot', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Manggarai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maranao', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Puyuma', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rejang Kayan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rembong', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yamdena', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yurok', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rusyn', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mopan Maya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Akawaio', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dieri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Western Arrernte', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ter Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ghotuo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tamil', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ineseño', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tukudede', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Shabo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khmer', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pitcairn-Norfolk', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tambora', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Burmese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Thai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Urdu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Persian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Evenki', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mongolian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yosondúa Mixtec', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yakut', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ottoman Turkish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Adzera', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yagnobi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kapingamarangi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pali', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Baluchi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pashto', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gooniyandi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Etruscan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wolio', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Campidanese Sardinian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Acehnese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Casiguran Dumagat Agta', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kanakanabu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yindjibarndi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mansaka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mongondow', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sika', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tiruray', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Havasupai-Walapai-Yavapai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Egyptian Arabic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Broome Pearling Lugger Pidgin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Guugu Yimidhirr', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Batak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Coastal Kadazan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gayo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hanunoo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Itawit', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kankanaey', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mayoyao Ifugao', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pangasinan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tontemboan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Western Bukidnon Manobo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mentawai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Komodo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Haroi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Roglai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rade', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Western Cham', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nenets', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Uab Meto', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Berawan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tunisian Arabic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aramaic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Muduapa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Norn', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bambara', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Angor', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dacian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Isan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wallisian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old East Slavic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mòcheno', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Xhosa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cherokee', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Karachay-Balkar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khakas', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kabardian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Polish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Akan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Warlpiri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('\'Are\'are', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Arosi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Tagbanwa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hano', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kambera', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Owa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tae\'', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tangoa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dhuwal', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tuvan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Woi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aneme Wake', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gamilaraay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tibetan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Tarahumara', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lingala', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hunsrik', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dorze', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gujarati', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bengali', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ontong Java', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lao', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Amharic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bontoc', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bughotu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dupaninan Agta', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('East Futuna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gela', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Isnag', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ivatan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lau', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lusi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Manam', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mussau-Emira', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nakanai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nukuoro', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Paiwan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Papora', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Roviana', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('To\'abaita', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Woleaian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nepali', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ligurian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ugaritic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Assamese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Punjabi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Oriya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Telugu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kazakh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Madurese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bau Bidayuh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alcozauca Mixtec', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kannada', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tagal Murut', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ngaanyatjarra', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Warrgamay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kaytetye', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Darkinjung', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sinhalese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rajasthani', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Newari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nogai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Woiwurrung', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Darling', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Martuthunira', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pitta-Pitta', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Armenian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Armenian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aleut', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bavarian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sindhi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Shelta', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ossetian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Avar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Libyan Arabic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chol', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Megleno-Romanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bandjalang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kalanga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kinyarwanda', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kusunda', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dharug', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kaurna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Uyghur', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Laki', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Awadhi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bhojpuri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Polabian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chaap Wuurong', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kamassian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Baba Malay', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aklanon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Angloromani', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Inupiak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Igbo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kongo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Komi-Zyrian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Esan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sherpa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Paumarí', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Japanese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maroon Spirit Language', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Potawatomi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Primitive Irish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Abkhaz', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kyrgyz', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Comanche', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zulgo-Gemzek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kabyle', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Eastern Cham', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gullah', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Oscan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sarcee', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kölsch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Algonquin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Abaza', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kashmiri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Eastern Arrernte', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wari\'', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Unserdeutsch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Malayalam', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Iranun', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Vurës', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pulaar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Fula', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Caló', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Plautdietsch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pahouin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lezgi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Antillean Creole', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Réunion Creole French', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bashkir', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Emilian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Saanich', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Koasati', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chuvash', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Swati', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Makhuwa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Twi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cheyenne', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mansi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Coatlán Mixe', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pirahã', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alune', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Banda (Indonesia)', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Banggai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Brunei Bisaya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Eritai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kemak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Leti', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Makasar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mandar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pamona', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Paulohi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sangir', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Siraya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sumbawa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yakan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Samogitian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tsakhur', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dolgan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kildin Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wageman', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Logudorese Sardinian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Moksha', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Emae', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Futuna-Aniwa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Niuafo\'ou', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('North Marquesan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Penrhyn', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Takuu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kamarian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Erzya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Motu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kwanyama', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ndonga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nganasan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mobilian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ida\'an', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rotokas', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tabassaran', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Unami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Udi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lakota', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dobu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Numbami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ende', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Coptic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alviri-Vidari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dyirbal', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cree', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Shoshone', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Southern Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kimaragang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pochutec', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tigrinya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Atlas Tamazight', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Meänkieli', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zoogocho Zapotec', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Kurdish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kikuyu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Meru', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lule Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Georgian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kabuverdianu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Abu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Xiang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Marwari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yanyuwa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Awabakal', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Classical Syriac', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tsonga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nyunga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Isthmus-Mecayapan Nahuatl', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sayula Popoluca', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Oromo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bihari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bima', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Minoan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Asilulu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bikol', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kulon-Pazeh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nauna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ngad\'a', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Saisiyat', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kirundi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chichewa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Marti Ke', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maléku Jaíka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tiwi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nage', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Fon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wemba-Wemba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ansus', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Papuma', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Marau', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Munggui', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ambai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Waropen', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kurudu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wabo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Vinza', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Xavante', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kadiwéu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Laal', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Worimi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kurnai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tlingit', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kalenjin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Udmurt', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Amaimon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('\'Auhelawa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Baruga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mazanderani', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Blackfoot', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tasmanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yidiny', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gabi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Moroccan Arabic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dhudhuroa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Phrygian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dadibi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Shuar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mi\'kmaq', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Arapaho', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Armenian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chinese Pidgin English', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Avestan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nhanda', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('ǃXóõ', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Dagara', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Aghul', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rutul', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dargwa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Shor', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kumyk', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Urum', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nootka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Russenorsk', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Achumawi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khowar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chiquitano', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tausug', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Nahuatl', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Miyako', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sumerian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Penobscot', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Akkadian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hittite', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mycenaean Greek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Creek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Luwian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Seraiki', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kamba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bunurong', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Ohlone', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('K\'iche\'', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('North Levantine Arabic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tamashek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Waray-Waray', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tumbuka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Montagnais', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yapese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Southern Altai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Jurchen', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Adele', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dinka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Berbice Creole Dutch', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Abanyom', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mende', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Comorian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bube', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Umbundu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Arawak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tshiluba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Persian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khanty', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Southern Ohlone', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Greenlandic Eskimo Pidgin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Taimyr Pidgin Russian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Turkic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zuni', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zenaga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tuwali Ifugao', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pohnpeian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Brahui', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ankave', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Korean', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lunda', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rungus', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lahu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bishnupriya Manipuri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hopi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Jingpho', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kalmyk', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Buryat', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alutiiq', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ilongot', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Thao', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dungan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Epigraphic Mayan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Slovincian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Phoenician', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Southeastern Tepehuan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('South Slavey', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gallurese Sardinian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ngawun', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Winnebago', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chinook', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bondei', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Zimba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Montana Salish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Laz', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rejang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sabah Bisaya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Eblaite', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lycian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dzongkha', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ket', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Svan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mingrelian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ammonite', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Edomite', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Moabite', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Punic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ge\'ez', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sichuan Yi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Baekje', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Harari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tigre', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Argobba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Powhatan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Umbrian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Buli (Indonesia)', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kowiai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tboli', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lydian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Massachusett', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Carian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bactrian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Santali', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Western Kayah', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kalami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Dhivehi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Buhid', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Vai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chukchi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alutor', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mambae', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Manchu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('South Levantine Arabic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Laurentian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hassaniya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Korean', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Seneca', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Balti', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nanai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Atayal', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nama', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Timugon Murut', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lozi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cowlitz', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Shan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old Lithuanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Haida', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ndali', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Koryak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tulu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ancient Macedonian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Southern Yukaghir', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Siberian Yupik', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mohawk', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nivkh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Limbu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mungaka', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Urartian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lacandon', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Leonese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Paelignian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ubykh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Venda', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pite Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khmu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kashaya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bikol Central', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Atikamekw', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Miami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maasai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Archi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Cappadocian Greek', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Hurrian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khvarshi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chagatai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Karakalpak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Weyewa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rusian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Muna', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Agutaynen', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Undetermined', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Beja', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lubuagan Kalinga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Andi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Central Dusun', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maricopa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yopno', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Monguor', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Malecite-Passamaquoddy', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bribri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Swabian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Vestinian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Makah', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('South Picene', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Knaanic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Marsian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Thai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Soqotri', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Comox', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Q\'anjob\'al', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gheg Albanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yonaguni', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Yukaghir', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Adioukrou', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Padoe', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Frankish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('West Flemish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Venetic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Faliscan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Volscian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lusitanian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Khazar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Southern Sama', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mara Chin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Southern Hindko', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gusii', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kuvi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sursurunga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wawa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Omaha-Ponca', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Osage', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Proto-Norse', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kalo Finnish Romani', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Median', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Assyrian Neo-Aramaic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Haitian Vodoun Culture Language', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ume Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kilivila', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lemnian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Marrucinian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Luba-Katanga', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lotud', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Angaataha', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pinyin', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lepontic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Alamblak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Ambulas', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kisar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Old South Arabian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sebat Bet Gurage', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kemi Sami', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Komi-Permyak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gazi', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Diitidaht', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Krio', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Embaloh', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Masbatenyo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sassarese Sardinian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Eteocretan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yaeyama', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Nyankole', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Middle Persian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Karamojong', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Parthian', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Banyumasan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Western Mari', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chru', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kavalan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tsou', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Rukai', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Saaroa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Brunei', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mbabaram', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Masaaba', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tsat', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Masiwang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Lun Bawang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tomadino', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tolaki', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Komering', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Babuza', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Kosraean', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Tambunan Dusun', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Calamian Tagbanwa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gorontalo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Uma', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Klamath-Modoc', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Eyak', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bisaya', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Taliabu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Huaorani', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sekar', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Yaqui', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Wintu', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pictish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bella Coola', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Burushaski', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Bura Mabang', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Krongo', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chakma', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pawnee', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mokpwe', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Karok', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Chinese', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Mandaic', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Noric', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Purepecha', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Gofa', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Northern Kurdish', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Austronesian Mor', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Silt\'e', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Pamlico', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Maykulan', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Sauraseni Prakrit', NULL);
INSERT INTO `lang` (`name`, `abr`) VALUES ('Talysh', NULL);
