package wiktionary.to.xml.full.jpa;

// Generated Oct 28, 2013 11:11:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Word generated by hbm2java
 */
@Entity
@Table(name = "word")
public class Word implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
    private Integer id;
    private String dataField;
    private Set<WordLang> wordLangs = new LinkedHashSet<WordLang>(0);

    public Word() {
    }

    public Word(String dataField, Set<WordLang> wordLangs) {
        this.dataField = dataField;
        this.wordLangs = wordLangs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "dataField", length = 45)
    public String getDataField() {
        return this.dataField;
    }

    public void setDataField(String dataField) {
        this.dataField = dataField;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "word")
    public Set<WordLang> getWordLangs() {
        return this.wordLangs;
    }

    public void setWordLangs(Set<WordLang> wordLangs) {
        this.wordLangs = wordLangs;
    }

}
