package wiktionary.to.xml.full.jpa;

// Generated Oct 28, 2013 11:11:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WordLang generated by hbm2java
 */
@Entity
@Table(name = "wordlang")
public class WordLang implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
    private Integer id;
    private Word word;
    private Lang lang;
    private String dataField;
    private Set<WordEtym> wordEtyms = new LinkedHashSet<WordEtym>(0);

    public WordLang() {
    }

    public WordLang(Word word, Lang lang) {
        this.word = word;
        this.lang = lang;
    }

    public WordLang(Word word, Lang lang, String dataField,
            Set<WordEtym> wordEtyms) {
        this.word = word;
        this.lang = lang;
        this.dataField = dataField;
        this.wordEtyms = wordEtyms;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    //@ManyToOne(fetch = FetchType.LAZY)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "word_id", nullable = false)
    public Word getWord() {
        return this.word;
    }

    public void setWord(Word word) {
        this.word = word;
    }

    //@ManyToOne(fetch = FetchType.LAZY)
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "lang_id", nullable = false)
    public Lang getLang() {
        return this.lang;
    }

    public void setLang(Lang lang) {
        this.lang = lang;
    }

    @Column(name = "dataField", length = 45)
    public String getDataField() {
        return this.dataField;
    }

    public void setDataField(String dataField) {
        this.dataField = dataField;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "wordLang")
    public Set<WordEtym> getWordEtyms() {
        return this.wordEtyms;
    }

    public void setWordEtyms(Set<WordEtym> wordEtyms) {
        this.wordEtyms = wordEtyms;
    }

}
