package wiktionary.to.xml.full.jpa;

// Generated Oct 28, 2013 11:11:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.NamedQuery;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lang generated by hbm2java
 */
@Entity
@Table(name = "lang")
@NamedQuery(name="Lang.findAll", query="SELECT s FROM Lang s")
public class Lang implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
    private Integer id;
    private String name;
    private String code;
    private String abr;
    private Set<WordLang> wordLangs = new LinkedHashSet<WordLang>(0);

    public Lang() {
    }

    public Lang(String name, String code, String abr) {
        this.name = name;
        this.code = code;
        this.abr = abr;
    }

    public Lang(String name, String code, String abr, Set<WordLang> wordLangs) {
        this.name = name;
        this.code = code;
        this.abr = abr;
        this.wordLangs = wordLangs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code", nullable = false, length = 6)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "abr", nullable = false, length = 6)
    public String getAbr() {
        return this.abr;
    }

    public void setAbr(String abr) {
        this.abr = abr;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lang")
    public Set<WordLang> getWordLangs() {
        return this.wordLangs;
    }

    public void setWordLangs(Set<WordLang> wordLangs) {
        this.wordLangs = wordLangs;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lang other = (Lang) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

}
